# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170313_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertesting',
            name='author',
        ),
        migrations.DeleteModel(
            name='Usertesting',
        ),
    ]
