# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usert_est', models.CharField(max_length=80)),
                ('result_question', models.TextField()),
            ],
        ),
    ]
