# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_savetest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savetest',
            old_name='usert_est',
            new_name='usert_test',
        ),
    ]
