# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170315_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savetest',
            old_name='usert_test',
            new_name='user_test',
        ),
    ]
