# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170315_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='savetest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='savetest',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
