# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170316_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savetest',
            old_name='created_date',
            new_name='testin_date',
        ),
        migrations.RenameField(
            model_name='savetest',
            old_name='published_date',
            new_name='testout_date',
        ),
    ]
