# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170321_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
